version: '3.8'

#services:
#  kafka-ui:
#    image: landoop/fast-data-dev
#    ports:
#      - "2181:2181"  # Zookeeper
#      - "3030:3030"  # Landoop UI
#      - "8081:8081"  # Schema Registry
#      - "8082:8082"  # Kafka REST Proxy
#      - "9581:9581"  # JMX (Kafka)
#      - "9582:9582"  # JMX (Schema Registry)
#      - "9583:9583"  # JMX (Kafka Connect)
#      - "9584:9584"  # JMX (Kafka REST Proxy)
#    environment:
#      ADV_HOST: "127.0.0.1" # Isso garante que o Kafka seja acessível via localhost
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      #      porta que o zookeeper está no container, no caso o kafka usa essa porta
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      #     para qualquer cliente no nosso host, eles precisam usar a porta 22181
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1